name: Tag

on:
  push:
    branches:
      - "master"
    paths:
      - "PKGBUILD"

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Build Arch Linux package
        run: make archbuild

      - name: Fetch Arch Linux package version
        id: pkg_version
        run: |
          PKG_VERSION=$(tar -xOf output/terraform-provider-njalla-*.pkg.tar.xz .PKGINFO | sed -n "s/pkgver = //p")
          echo "::set-output name=VERSION::v$PKG_VERSION"

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'actions@github.com'

      - name: Check tag
        id: check_tag
        shell: bash
        run: >
          if [[ $(git ls-remote origin "refs/tags/${{ steps.pkg_version.outputs.VERSION }}") ]]; then
            echo "::set-output name=exists::true";
          else
            echo "::set-output name=exists::false";
          fi

      - name: Tag version
        if: steps.check_tag.outputs.exists == 'false'
        run: >
          git tag -m ${{ steps.pkg_version.outputs.VERSION }}
          -a ${{ steps.pkg_version.outputs.VERSION }}


      - name: Push tag
        if: steps.check_tag.outputs.exists == 'false'
        run: git push origin ${{ steps.pkg_version.outputs.VERSION }}
